const Strings = {
    sendOtpText: 'Send OTP',
    Skip: 'Skip',
    ContinueGoogle: 'Continue with Email',
    Facebook: 'Facebook',
    Google: 'Google',
    Terms1: 'By continuing, you agree to our',
    Terms2: 'Terms of Service',
    Terms3: 'Privacy Policy',
    Terms4: 'Content Policy',

    OtpSentText: 'We have sent a verification code to ',
    VerifyText: 'Verify',

    DishContainerHeader: 'Eat what makes you happy',

    FoodPageOrderText: 'Goto Order',

    RestaurantCardHeaderText: 'restaurants around you',
    priceForYou: 'for one',
    mxSafety: 'MAX SAFELTY',
    delivery: 'DELIVERY',

    bestSeller: 'Bestseller',
    AddonReadMore: '...read more',
    addonText: 'Add On',
    addonChoosingText: 'You can choose upto 4 options',
    ExtraProtienText: 'Choose Your Protien',
    ButtonAddText: 'Add ₹',

    deliveryInText: 'Delivery in',
    AddInstructionText: 'Add cooking instructions (optional)',
    Offers: 'Offers',
    SelectPromo: 'Select a promo code ',
    promoCode: 'Save 59.70 with code ZOMATOSAFETY ',
    viewOffer: 'View Offers',
    tipValet: 'Please tip your valet',
    tipValetText: 'Support your valet and make their day! 100% of your tip will be transferred to your valet',
    mostTipped: 'MOST TIPPED',
    ItemTotal: 'Item Total',
    deliveryCharge: 'Delivery Charge',
    taxes: 'Taxes',
    donateText: 'Donate ₹3 to Feeding India Foundation',
    addText: 'Add',
    grandTotal: 'Grand Total',
    emergencyTextHeader: 'This order is related to a COVID-19 emergency',
    covidText: 'This order will be prepared and delivered on priority. It will be a contactless delivery. #RestaurantsAgainstCOVID',
    TreatText: 'Treat this as an ambulance and please don’t misuse it.',
    DeliveryInstruction: 'Delivery instructions',
    changeText: 'Change',
    handMeText: 'Hand me the Order',
    voiceDirection: 'Add Voice Direction',
    yourDetails: 'Your details',
    forSomeOne: 'Order for someone else',
    personalizedMessage: 'Send personalized message and e-card',
    ClimateDelivery: 'Climate conscious delivery',
    climateDescription: 'We fund environmental projects to offset the carbon footprint of our deliveries.',
    knowMore: 'Know more',
    nonReturnableText: 'Orders once placed cannot be cancelled and are non-refundable.',
    payUsing: 'PAY USING',
    googlePay: 'Google Pay',
    totalText: 'TOTAL',
    placeOrder: 'Place Order',


    searchbarPlaceholder: 'Restaurant name, cuisine, or a dish...',

    Home: 'Home',
    Chat: 'Chat',
    Settings: 'Settings',
    Help: 'Help',
    mode: 'Mode Change',
    logOut: 'Log out',

    photos: 'PHOTOS',

    max: 'Max ',
    Safety: 'Safety',
    pro: 'PRO',
    Cuisines: 'Cuisines',
    Rating: 'Rating',
    Popular: 'Popular',

    dining: 'DINING',
    reviewing: 'REVIEWS',
    modeDeliery: 'MODE',
    deliveryTxt: 'delivery',
    time: 'TIME',
    min:'mins',
    offersTxt: 'OFFERS',
    addCapTxt : 'ADD',
    viewall : 'view all (3)',
    distanceCharge: 'distance charge',
    veg : 'Veg',
    egg: 'Egg',
    recomended : 'Recomeneded',
    mustTry : ' Must Try',
    offUpto : '% OFF up to ₹',
    useCode : 'Use code ZOMSAFETY on orders with items worth ₹159 or more',
    item : 'ITEM',
    plusAxes: 'plus axes',
    viewCart: 'View Cart',
}
export default Strings